version: "3.9"
networks:
  exchnet:
    ipam:
      config:
        - subnet: 192.168.55.0/24
services:
  app:
    build: "./environment/app/"
    volumes:
      - ./:/code
    networks:
        exchnet:
          ipv4_address: 192.168.55.5
  nginx:
    image: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./environment/nginx:/etc/nginx/conf.d
      - ./:/code
    networks:
        exchnet:
          ipv4_address: 192.168.55.2
  redis:
    image: "redis:alpine"
    networks:
        exchnet:
          ipv4_address: 192.168.55.3
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
        exchnet:
          ipv4_address: 192.168.55.4
volumes:
  mysql-data: